### ISSUE TITLE
Handle int excptions to zero

### ISSUE THREAD

**Issue by hginzel** [CZ-NIC/pyed#3]
```
echo -e 'a,1\nb,c' |pz 'int(s.split(",")[1])+2'
Exception: <class 'ValueError'> invalid literal for int() with base 10: 'b' on line: a,b
```
produces
```
3
Exception: <class 'ValueError'> invalid literal for int() with base 10: 'c' on line: b,c
```

**Comment by e3rd** [comment]
Hi, I suspect this may produce an unexpected behaviour.

Note that using the quiet flag suppresses the warning which may be the desired output (like in the case you sum the results or something).
```bash
$ echo -e 'a,1\nb,c' |pz 'int(s.split(",")[1])+2' -q
3
```

If that does not fit your needs, would you be so kind and post a real-world use case where you'd prefer zeroes over empty lines? If a flag or something for exception handling existed, how would you use it?

**Comment by e3rd** [comment]
If you react, I'll re-open the issue, thanks!
