### ISSUE TITLE
config file/env variable to handle custom imports

### ISSUE THREAD

**Issue by kidpixo** [CZ-NIC/pyed#7]
Hi,
thanks for pz, this is aswsome!

I would find useful to have config file/env variable to handle imports users want to always have.

i.e. : 

I like to use the [rich](https://pypi.org/project/rich/) package and currently I must use the `--setup` keyword

```
echo 50 | pz \
    --setup 'from rich.progress import track;import time' \
    'for n in track(range(n)):  time.sleep(0.1)'
```
I suggest to read an `$XDG_CONFIG_HOME/pd/import.py` file or and env variable `export PZ_IMPORT='from rich.progress import track'`to have my precious import always available.

**Comment by e3rd** [comment]
Neat idea, thanks! I'll do some performance tests and consider security aspects first.

**Comment by e3rd** [comment]
Despite an uncomplicated implementation, I'm still considering the security. An attacker who changes the env variable or the contents of the file might let you launch arbitrary code.

One partial solution would be to introduce a flag, allowing the use of the external sources. Like `-I` for insecure. Would you mind writing `pz -I` so that the utility search through the env variable or such compromise would not help you?

```bash
$ export PZ_SETUP='from rich.progress import track; from time import sleep'
$ pz  'for n in track(range(n)): sleep(0.1)'
```

**Comment by kidpixo** [comment]
> Despite an uncomplicated implementation, I'm still considering the security. An attacker who changes the env variable or the contents of the file might let you launch arbitrary code.

Ah right , I didn't thought this  will be evaluated in python without explicit user check, nice catch!

This is a similar issue like the infamous log4j bug :sweat_smile: : let execute arbitrary code.

I'm totally fine with using `-I`, leaving the secure implementation  as default.
I would put your phrase above as warning in the docs.

**Comment by e3rd** [comment]
Could you please check current master suits you?

**Comment by kidpixo** [comment]
Thanks for the commit!

It seems pz sees `PZ_SETUP` but something is not working : 

```$ export PZ_SETUP='from rich.progress import track; from time import sleep'
$ env | grep PZ
PZ_SETUP=from rich.progress import track; from time import sleep
$ echo 50 | pz -I 'for n in track(range(n)):  time.sleep(0.1)'
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
```
It seems the loop is not executed.
This works as before

```
$ echo 50 | pz -v --setup 'from rich.progress import track;import time'     'for n in track(range(n)):  time.sleep(0.1)'
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
50
```

Are the `--setup` and `--insecure` implementation different?

![image](https://user-images.githubusercontent.com/2255209/160255715-c3d36b42-0deb-48a5-8212-90ab0260ac12.png)

**Comment by kidpixo** [comment]
ok, this is strange , or maybe it is just me not getting how pz works :

```$ echo 3 | python pz -I 'for n in range(n):   print(i)'
0
0
0
3

$ echo 3 | python pz 'for n in range(n):   print(i)'
0
0
0
3
```

**Comment by kidpixo** [comment]
It seems that with `-I` it just skips the loop 

```
$ time echo 10 | pz -v -I 'for n in range(n):  time.sleep(0.1)'
Importing time from time
10

real    0m0.202s
user    0m0.182s
sys     0m0.021s
```
```
$ time echo 10 | pz  --setup 'from rich.progress import track;import time' 'for n in range(n):  time.sleep(0.1)'
10

real    0m1.211s
user    0m0.186s
sys     0m0.025s
```

**Comment by e3rd** [comment]
I got it! In PZ_SETUP you've imported `sleep`, not `time`. Then, you used `time.sleep`, thereforce an auto import took place and the line get reprocessed. But as you redeclared n in the cycle `for N in ...`, the `n` variable was set as 0 in the second cycle. This would work `for i in track(range(n)):  time.sleep(0.1)` (see `i` instead of `n`).

```bash
echo 50 | PZ_SETUP='from rich.progress import track; from time import sleep' pz -I 'for i in track(range(n)):  sleep(0.1)'`
```
