### ISSUE TITLE
MANIFEST.in → setup.py

### ISSUE THREAD

**Issue by e3rd** [CZ-NIC/pyed#8]
Hello @thewchan ,
you've introduced MANIFEST.in file in #5 . I did some probe and it seems MANIFEST.in file is not very useful. As I tend to keep the number of files on the minimum, would you mind to refactor that to the setup.py (ex: https://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script )? Or is there any advantage in using MANIFEST.in?

Thanks!

**Comment by thewchan** [comment]
Hi, sorry I should have elaborate. I think I was trying to put this package on Conda Forge, but they have a requirement that the license file is bundled with the sdist archive. The MANIFEST.in file ensures that, as last I check the license file is present in the GH repo but not in the sdist.

**Comment by e3rd** [comment]
Will you have time to put it in the setup.py in the next days please or are you busy?

**Comment by thewchan** [comment]
If you are okay with including MANIFEST.in, then that's all there is to it; no changes needed in setup.py

https://packaging.python.org/en/latest/guides/using-manifest-in/

**Comment by e3rd** [comment]
As I tend to keep the number of files on the minimum and if you state no advantage in using the MANIFEST.in, I'd prefer to remove it. Hence I've asked if you have time to do that or if you are busy.

**Comment by thewchan** [comment]
The advantage is that including it would package in the license file into the sdist, allowing the package to be sustainably put on Conda Forge. But I understand if that's not to your interest.

**Comment by thewchan** [comment]
I see what you're saying now; you prefer a PR on the `setup.cfg` file instead? I can try that as well.

**Comment by e3rd** [comment]
Thanks for the PR, however I rejected it because it did not discard the MANIFEST.in file which was the main issue. I've removed it, put the license in the setup.cfg and published on PyPi. It seems to me the LICENSE.txt is now present in the sdist package – will you please check it works now on the Conda Forge (I have no experience with)?
https://pypi.org/project/pz/1.1.0rc1

**Comment by e3rd** [comment]
if you wont reply i will treat this as solved

**Comment by thewchan** [comment]
Sorry, I missed this comment earlier. Thanks so much for accommodating. Please mark as solved.

**Comment by e3rd** [comment]
Thanks for the help, thewchan!
